In [1]:
from Tidy_Data_new import *
# from AdvancedModel_helpers import *

In [2]:
if not os.path.exists("csv"):
    os.makedirs("csv")
for year in [2020,2021,2022]: # 2020 has been excluded to be reserved as the test set
    read_a_season("../nhl_data/",year).to_csv('csv/tidy_{season}.csv'.format(season = year), sep = ',', index = False)

  0%|          | 0/8951 [00:00<?, ?it/s]

100%|██████████| 8951/8951 [00:20<00:00, 428.85it/s]
100%|██████████| 8951/8951 [00:38<00:00, 234.22it/s]
100%|██████████| 8951/8951 [00:36<00:00, 242.05it/s]

In [3]:
directory = 'csv'

# Get a list of csv file names within the directory
csv_files = [f for f in os.listdir(directory) if f.endswith('.csv')]

# Sort the list of csv files
csv_files.sort()

# List to hold your DataFrames
dataframes_list = []

# Loop over the sorted list of csv files with tqdm for progress indication
for filename in tqdm(csv_files, desc="Loading files", unit="file"):
    file_path = os.path.join(directory, filename)
    df = pd.read_csv(file_path)

    # Filter the DataFrame to only include rows where 5th and 6th digits of 'game_id' are '02' (Regular Season)

    dataframes_list.append(df)

# Concatenate all the DataFrames in the list into a single DataFrame
test_df = pd.concat(dataframes_list, ignore_index=True)

# Reset the index of the sorted DataFrame
test_df = test_df.reset_index(drop=True)

Loading files: 100%|██████████| 3/3 [00:00<00:00,  4.26file/s]

In [4]:
test_df.head(10)

,game_id,home_name,away_name,home_score,away_score,home_or_away,event_idx,play_type,shot_type,shot_dist,game_time,period,period_time_rem,coordinate,shooter_id,goalie_id,empty_Net,rink_side,angle_net,is_goal
0,2020020001,Penguins,Flyers,0,0,0,53,Shot,Wrist Shot,32.649655,2021-01-13T22:30:00Z,1,19:44,"{'x': -74, 'y': 29}",8478439,8477465.0,0,right,-62.650124,0
1,2020020001,Penguins,Flyers,0,0,1,9,Shot,Wrist Shot,47.169906,2021-01-13T22:30:00Z,1,19:26,"{'x': 49, 'y': -25}",8478542,8479394.0,0,left,-32.005383,0
2,2020020001,Penguins,Flyers,0,0,0,55,Shot,Backhand,48.270074,2021-01-13T22:30:00Z,1,18:55,"{'x': -52, 'y': -31}",8480797,8477465.0,0,right,39.957549,0
3,2020020001,Penguins,Flyers,0,0,1,62,Shot,Snap Shot,60.307545,2021-01-13T22:30:00Z,1,17:09,"{'x': 43, 'y': 39}",8478542,8479394.0,0,left,40.292148,0
4,2020020001,Penguins,Flyers,0,0,0,64,Shot,Slap Shot,54.203321,2021-01-13T22:30:00Z,1,16:31,"{'x': -46, 'y': 33}",8479026,8477465.0,0,right,-37.504142,0
5,2020020001,Penguins,Flyers,0,0,0,65,Shot,Slap Shot,36.878178,2021-01-13T22:30:00Z,1,16:16,"{'x': -53, 'y': 8}",8473512,8477465.0,0,right,-12.528808,0
6,2020020001,Penguins,Flyers,0,0,0,66,Shot,Wrist Shot,19.235384,2021-01-13T22:30:00Z,1,16:14,"{'x': -70, 'y': -3}",8479026,8477465.0,0,right,8.972627,0
7,2020020001,Penguins,Flyers,0,0,1,67,Shot,Wrist Shot,46.097722,2021-01-13T22:30:00Z,1,15:30,"{'x': 59, 'y': -35}",8478043,8479394.0,0,left,-49.398705,0
8,2020020001,Penguins,Flyers,0,0,0,68,Shot,Wrist Shot,41.036569,2021-01-13T22:30:00Z,1,15:21,"{'x': -59, 'y': -28}",8478439,8477465.0,0,right,43.025066,0
9,2020020001,Penguins,Flyers,0,1,1,70,Goal,Snap Shot,9.433981,2021-01-13T22:30:00Z,1,14:48,"{'x': 81, 'y': -5}",8476873,8479394.0,0,left,-32.005383,1