In [1]:
from Tidy_Data_new import *
# from AdvancedModel_helpers import *

In [2]:
if not os.path.exists("csv"):
    os.makedirs("csv")
for year in [2020,2021,2022]: # 2020 has been excluded to be reserved as the test set
    read_a_season("../nhl_data/",year).to_csv('csv/tidy_{season}.csv'.format(season = year), sep = ',', index = False)

  0%|          | 0/8951 [00:00<?, ?it/s]

100%|██████████| 8951/8951 [00:15<00:00, 579.71it/s]
100%|██████████| 8951/8951 [00:34<00:00, 260.72it/s]
100%|██████████| 8951/8951 [00:34<00:00, 260.37it/s]

In [3]:
directory = 'csv'

# Get a list of csv file names within the directory
csv_files = [f for f in os.listdir(directory) if f.endswith('.csv')]

# Sort the list of csv files
csv_files.sort()

# List to hold your DataFrames
dataframes_list = []

# Loop over the sorted list of csv files with tqdm for progress indication
for filename in tqdm(csv_files, desc="Loading files", unit="file"):
    file_path = os.path.join(directory, filename)
    df = pd.read_csv(file_path)

    # Filter the DataFrame to only include rows where 5th and 6th digits of 'game_id' are '02' (Regular Season)

    dataframes_list.append(df)

# Concatenate all the DataFrames in the list into a single DataFrame
test_df = pd.concat(dataframes_list, ignore_index=True)

# Sort the DataFrame first by 'game_id' and then by 'event_idx'
test_df= test_df.sort_values(by=['game_id', 'event_idx'])

# Reset the index of the sorted DataFrame
test_df = test_df.reset_index(drop=True)

Loading files: 100%|██████████| 3/3 [00:00<00:00,  5.70file/s]

In [4]:
test_df

,game_id,event_idx,play_type,shot_type,shot_dist,game_time,period,period_time_rem,coordinate,shooter_id,goalie_id,empty_Net,rink_side,angle_net,is_goal
0,2020020001,9,Shot,Wrist Shot,47.169906,2021-01-13T22:30:00Z,1,19:26,"{'x': 49, 'y': -25}",8478542,8479394.0,0,left,-32.005383,0
1,2020020001,34,Shot,Snap Shot,63.812225,2021-01-13T22:30:00Z,1,08:21,"{'x': -35, 'y': -34}",8477462,8477465.0,0,right,32.195734,0
2,2020020001,42,Shot,Wrist Shot,29.068884,2021-01-13T22:30:00Z,1,04:18,"{'x': 87, 'y': 29}",8471675,8479394.0,0,left,86.054814,0
3,2020020001,53,Shot,Wrist Shot,32.649655,2021-01-13T22:30:00Z,1,19:44,"{'x': -74, 'y': 29}",8478439,8477465.0,0,right,-62.650124,0
4,2020020001,55,Shot,Backhand,48.270074,2021-01-13T22:30:00Z,1,18:55,"{'x': -52, 'y': -31}",8480797,8477465.0,0,right,39.957549,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324175,2022030415,796,Shot,Wrist Shot,126.826653,2023-06-14T00:00:00Z,3,02:01,"{'x': -32, 'y': 38}",8479372,8478499.0,0,left,17.434875,0
324176,2022030415,1001,Shot,Wrist Shot,61.400326,2023-06-14T00:00:00Z,3,01:05,"{'x': -36, 'y': -31}",8477447,8475683.0,0,right,30.323607,0
324177,2022030415,1002,Goal,Wrist Shot,5.830952,2023-06-14T00:00:00Z,3,01:02,"{'x': -86, 'y': 5}",8478462,8475683.0,0,right,-59.036243,1
324178,2022030415,1055,Shot,Wrist Shot,6.403124,2023-06-14T00:00:00Z,3,05:31,"{'x': 84, 'y': 4}",8479066,8478499.0,0,left,38.659808,0
324179,2022030415,1056,Shot,Wrist Shot,21.470911,2023-06-14T00:00:00Z,3,07:56,"{'x': -99, 'y': -19}",8476448,8475683.0,0,right,62.241459,0